# Generated by Django 2.2.5 on 2019-10-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=75)),
                ('city', models.CharField(blank=True, max_length=75)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ArrivingFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriving_airport', models.CharField(blank=True, max_length=125)),
                ('arriving_airline', models.CharField(blank=True, max_length=125)),
                ('arriving_flight_number', models.CharField(blank=True, max_length=25)),
                ('arriving_date', models.DateTimeField()),
                ('arriving_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(blank=True, max_length=150)),
                ('cc_num', models.CharField(max_length=16, unique=True)),
                ('cc_exp', models.DateTimeField()),
                ('cc_zip', models.CharField(max_length=25)),
                ('cc_scode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DepartingFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departing_airport', models.CharField(blank=True, max_length=125)),
                ('departing_airline', models.CharField(blank=True, max_length=125)),
                ('departing_flight_number', models.CharField(blank=True, max_length=25)),
                ('departing_date', models.DateTimeField()),
                ('departing_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_num', models.CharField(blank=True, max_length=25, unique=True)),
                ('dl_exp', models.DateTimeField()),
                ('dl_dob', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualInformation',
            fields=[
                ('individual_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('cell_phone', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cust_address', models.ForeignKey(blank=True, on_delete='CASCADE', to='adobe_app.Address')),
                ('cust_credit_card', models.ForeignKey(blank=True, on_delete='CASCADE', to='adobe_app.CreditCard')),
                ('cust_driver_license', models.ForeignKey(blank=True, on_delete='CASCADE', to='adobe_app.DriverLicense')),
            ],
        ),
        migrations.CreateModel(
            name='RentalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=50)),
                ('dl_num', models.CharField(blank=True, max_length=25)),
                ('dl_exp', models.DateTimeField()),
                ('dl_dob', models.DateTimeField()),
                ('cc_num', models.CharField(blank=True, max_length=16)),
                ('cc_exp', models.DateTimeField()),
                ('cc_zip', models.CharField(blank=True, max_length=25)),
                ('org_address', models.ForeignKey(blank=True, on_delete='CASCADE', to='adobe_app.Address')),
                ('org_representative', models.ForeignKey(on_delete='CASCADE', to='adobe_app.IndividualInformation')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=125)),
                ('dl_info', models.ForeignKey(blank=True, on_delete='CASCADE', to='adobe_app.DriverLicense')),
            ],
        ),
    ]
