# Generated by Django 2.2.5 on 2019-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinformation',
            name='cust_address',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='adobe_app.Address'),
        ),
    ]
