# Generated by Django 2.2.5 on 2019-10-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0002_auto_20191003_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinformation',
            name='cust_credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='adobe_app.CreditCard'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_address',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='adobe_app.Address'),
        ),
    ]
