# Generated by Django 2.2.5 on 2019-10-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0005_auto_20191003_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivingDepartingFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriving_airport', models.CharField(max_length=125)),
                ('arriving_airline', models.CharField(max_length=125)),
                ('arriving_flight_number', models.CharField(max_length=25)),
                ('arriving_date_time', models.DateTimeField()),
                ('departing_airport', models.CharField(max_length=125)),
                ('departing_airline', models.CharField(max_length=125)),
                ('departing_flight_number', models.CharField(max_length=25)),
                ('departing_date_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ArrivingFlight',
        ),
        migrations.DeleteModel(
            name='DepartingFlight',
        ),
    ]
