# Generated by Django 2.2.5 on 2019-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0006_auto_20191003_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='arriving_airline',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='arriving_airport',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='arriving_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='arriving_flight_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='departing_airline',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='departing_airport',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='departing_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='arrivingdepartingflight',
            name='departing_flight_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
