# Generated by Django 2.2.5 on 2019-10-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0009_auto_20191003_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cc_exp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dl_dob',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dl_exp',
            field=models.DateTimeField(blank=True),
        ),
    ]
