# Generated by Django 2.2.4 on 2019-11-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobe_app', '0010_auto_20191003_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='additional_driver',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='airport_access_fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='cleaning_fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='damage_charge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='drop_fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='fuel_charge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='grand_total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='late_charge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='license_tax',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='mexico_insurance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='mileage_over_charge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='num_of_vans',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='other_charges',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='rate_charge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='rental_date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='rental_date_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='sales_tax',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='subtotal_in',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='subtotal_out',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='surcharge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='total_due',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vanrental',
            name='under_age',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book name')),
                ('author_email', models.EmailField(blank=True, max_length=75, verbose_name='Author email')),
                ('imported', models.BooleanField(default=False)),
                ('published', models.DateField(blank=True, null=True, verbose_name='Published')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='adobe_app.Author')),
                ('categories', models.ManyToManyField(blank=True, to='adobe_app.Category')),
            ],
        ),
    ]
